//
// Generated file, do not edit! Created by nedtool 5.6 from inet/linklayer/common/MacAddressTag.msg.
//

#ifndef __INET_MACADDRESSTAG_M_H
#define __INET_MACADDRESSTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class MacAddressTagBase;
class MacAddressReq;
class MacAddressInd;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

#include "inet/linklayer/common/MacAddress_m.h" // import inet.linklayer.common.MacAddress


namespace inet {

/**
 * Class generated from <tt>inet/linklayer/common/MacAddressTag.msg:12</tt> by nedtool.
 * <pre>
 * class MacAddressTagBase extends TagBase
 * {
 *     MacAddress srcAddress;      // may be unspecified
 *     MacAddress destAddress; // always specified
 * }
 * </pre>
 */
class INET_API MacAddressTagBase : public ::inet::TagBase
{
  protected:
    MacAddress srcAddress;
    MacAddress destAddress;

  private:
    void copy(const MacAddressTagBase& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MacAddressTagBase&);

  public:
    MacAddressTagBase();
    MacAddressTagBase(const MacAddressTagBase& other);
    virtual ~MacAddressTagBase();
    MacAddressTagBase& operator=(const MacAddressTagBase& other);
    virtual MacAddressTagBase *dup() const override {return new MacAddressTagBase(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const MacAddress& getSrcAddress() const;
    virtual MacAddress& getSrcAddressForUpdate() { return const_cast<MacAddress&>(const_cast<MacAddressTagBase*>(this)->getSrcAddress());}
    virtual void setSrcAddress(const MacAddress& srcAddress);
    virtual const MacAddress& getDestAddress() const;
    virtual MacAddress& getDestAddressForUpdate() { return const_cast<MacAddress&>(const_cast<MacAddressTagBase*>(this)->getDestAddress());}
    virtual void setDestAddress(const MacAddress& destAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MacAddressTagBase& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MacAddressTagBase& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/linklayer/common/MacAddressTag.msg:21</tt> by nedtool.
 * <pre>
 * //
 * // Determines the source and destination MAC addresses for an outgoing packet.
 * //
 * class MacAddressReq extends MacAddressTagBase
 * {
 * }
 * </pre>
 */
class INET_API MacAddressReq : public ::inet::MacAddressTagBase
{
  protected:

  private:
    void copy(const MacAddressReq& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MacAddressReq&);

  public:
    MacAddressReq();
    MacAddressReq(const MacAddressReq& other);
    virtual ~MacAddressReq();
    MacAddressReq& operator=(const MacAddressReq& other);
    virtual MacAddressReq *dup() const override {return new MacAddressReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MacAddressReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MacAddressReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/linklayer/common/MacAddressTag.msg:28</tt> by nedtool.
 * <pre>
 * //
 * // Specifies the source and destination MAC addresses for an incoming packet.
 * //
 * class MacAddressInd extends MacAddressTagBase
 * {
 * }
 * </pre>
 */
class INET_API MacAddressInd : public ::inet::MacAddressTagBase
{
  protected:

  private:
    void copy(const MacAddressInd& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MacAddressInd&);

  public:
    MacAddressInd();
    MacAddressInd(const MacAddressInd& other);
    virtual ~MacAddressInd();
    MacAddressInd& operator=(const MacAddressInd& other);
    virtual MacAddressInd *dup() const override {return new MacAddressInd(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MacAddressInd& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MacAddressInd& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_MACADDRESSTAG_M_H

