//
// Generated file, do not edit! Created by nedtool 5.6 from inet/routing/rip/RipPacket.msg.
//

#ifndef __INET_RIPPACKET_M_H
#define __INET_RIPPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

struct RipEntry;
class RipPacket;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address


namespace inet {

// cplusplus {{
const B RIP_HEADER_SIZE = B(4);
const B RIP_RTE_SIZE = B(20);
// }}

/**
 * Enum generated from <tt>inet/routing/rip/RipPacket.msg:35</tt> by nedtool.
 * <pre>
 * //
 * // RIP commands
 * //
 * enum RipCommand
 * {
 *     RIP_REQUEST = 1;
 *     RIP_RESPONSE = 2;
 * }
 * </pre>
 */
enum RipCommand {
    RIP_REQUEST = 1,
    RIP_RESPONSE = 2
};

/**
 * Enum generated from <tt>inet/routing/rip/RipPacket.msg:43</tt> by nedtool.
 * <pre>
 * //
 * // Address Family constants
 * //
 * enum RipAf
 * {
 *     RIP_AF_NONE = 0;
 *     RIP_AF_INET = 2;
 *     // RIP_AF_AUTH = 0xFFFF;
 * }
 * </pre>
 */
enum RipAf {
    RIP_AF_NONE = 0,
    RIP_AF_INET = 2
};

/**
 * Struct generated from inet/routing/rip/RipPacket.msg:55 by nedtool.
 */
struct INET_API RipEntry
{
    RipEntry();
    inet::RipAf addressFamilyId;
    unsigned short routeTag;
    L3Address address;
    int prefixLength;
    L3Address nextHop;
    unsigned int metric;
};

// helpers for local use
void INET_API __doPacking(omnetpp::cCommBuffer *b, const RipEntry& a);
void INET_API __doUnpacking(omnetpp::cCommBuffer *b, RipEntry& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RipEntry& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RipEntry& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>inet/routing/rip/RipPacket.msg:70</tt> by nedtool.
 * <pre>
 * //
 * // RIPv2 packet
 * //
 * // note: Authentication entry is not allowed
 * //
 * class RipPacket extends FieldsChunk
 * {
 *     RipCommand command;
 *     // version is fixed: 2
 *     RipEntry entry[];
 * }
 * </pre>
 */
class INET_API RipPacket : public ::inet::FieldsChunk
{
  protected:
    inet::RipCommand command = static_cast<inet::RipCommand>(-1);
    RipEntry *entry = nullptr;
    size_t entry_arraysize = 0;

  private:
    void copy(const RipPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RipPacket&);

  public:
    RipPacket();
    RipPacket(const RipPacket& other);
    virtual ~RipPacket();
    RipPacket& operator=(const RipPacket& other);
    virtual RipPacket *dup() const override {return new RipPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual inet::RipCommand getCommand() const;
    virtual void setCommand(inet::RipCommand command);
    virtual void setEntryArraySize(size_t size);
    virtual size_t getEntryArraySize() const;
    virtual const RipEntry& getEntry(size_t k) const;
    virtual RipEntry& getEntryForUpdate(size_t k) { handleChange();return const_cast<RipEntry&>(const_cast<RipPacket*>(this)->getEntry(k));}
    virtual void setEntry(size_t k, const RipEntry& entry);
    virtual void insertEntry(const RipEntry& entry);
    virtual void insertEntry(size_t k, const RipEntry& entry);
    virtual void eraseEntry(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RipPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RipPacket& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_RIPPACKET_M_H

