//
// Generated file, do not edit! Created by nedtool 5.6 from inet/common/Simsignals.msg.
//

#ifndef __INET_SIMSIGNALS_M_H
#define __INET_SIMSIGNALS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class PacketDropDetails;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs


namespace inet {

/**
 * Enum generated from <tt>inet/common/Simsignals.msg:10</tt> by nedtool.
 * <pre>
 * enum PacketDropReason
 * {
 *     ADDRESS_RESOLUTION_FAILED = 0;
 *     FORWARDING_DISABLED = 1;
 *     HOP_LIMIT_REACHED = 2;
 *     INCORRECTLY_RECEIVED = 3;
 *     INTERFACE_DOWN = 4;
 *     NO_INTERFACE_FOUND = 5;
 *     NO_ROUTE_FOUND = 6;
 *     NOT_ADDRESSED_TO_US = 7;
 *     QUEUE_OVERFLOW = 8;
 *     RETRY_LIMIT_REACHED = 9;
 *     LIFETIME_EXPIRED = 10;
 *     CONGESTION = 11;
 *     NO_PROTOCOL_FOUND = 12;
 *     NO_PORT_FOUND = 13;
 *     OTHER_PACKET_DROP = 99;
 * }
 * </pre>
 */
enum PacketDropReason {
    ADDRESS_RESOLUTION_FAILED = 0,
    FORWARDING_DISABLED = 1,
    HOP_LIMIT_REACHED = 2,
    INCORRECTLY_RECEIVED = 3,
    INTERFACE_DOWN = 4,
    NO_INTERFACE_FOUND = 5,
    NO_ROUTE_FOUND = 6,
    NOT_ADDRESSED_TO_US = 7,
    QUEUE_OVERFLOW = 8,
    RETRY_LIMIT_REACHED = 9,
    LIFETIME_EXPIRED = 10,
    CONGESTION = 11,
    NO_PROTOCOL_FOUND = 12,
    NO_PORT_FOUND = 13,
    OTHER_PACKET_DROP = 99
};

/**
 * Class generated from <tt>inet/common/Simsignals.msg:29</tt> by nedtool.
 * <pre>
 * class PacketDropDetails extends cObject
 * {
 *     PacketDropReason reason;
 *     int limit = -1;
 * }
 * </pre>
 */
class INET_API PacketDropDetails : public ::omnetpp::cObject
{
  protected:
    inet::PacketDropReason reason = static_cast<inet::PacketDropReason>(-1);
    int limit = -1;

  private:
    void copy(const PacketDropDetails& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PacketDropDetails&);

  public:
    PacketDropDetails();
    PacketDropDetails(const PacketDropDetails& other);
    virtual ~PacketDropDetails();
    PacketDropDetails& operator=(const PacketDropDetails& other);
    virtual PacketDropDetails *dup() const override {return new PacketDropDetails(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual inet::PacketDropReason getReason() const;
    virtual void setReason(inet::PacketDropReason reason);
    virtual int getLimit() const;
    virtual void setLimit(int limit);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacketDropDetails& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacketDropDetails& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_SIMSIGNALS_M_H

