//
// Generated file, do not edit! Created by nedtool 5.6 from inet/transportlayer/tcp_common/TcpHeader.msg.
//

#ifndef __INET__TCP_TCPHEADER_M_H
#define __INET__TCP_TCPHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {
namespace tcp {

class SackItem;
class Sack;
class TcpOption;
class TcpOptionEnd;
class TcpOptionNop;
class TcpOptionMaxSegmentSize;
class TcpOptionWindowScale;
class TcpOptionSackPermitted;
class TcpOptionSack;
class TcpOptionTimestamp;
class TcpOptionUnknown;
class TcpHeader;
} // namespace tcp
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/transportlayer/common/CrcMode_m.h" // import inet.transportlayer.common.CrcMode

#include "inet/transportlayer/contract/TransportHeaderBase_m.h" // import inet.transportlayer.contract.TransportHeaderBase


namespace inet {
namespace tcp {

// cplusplus {{
const B TCP_MIN_HEADER_LENGTH = B(20);  // default TCP header length: 20 bytes without options
const B TCP_MAX_HEADER_LENGTH = B(60);  // maximum TCP header length (base + options): 60 = 15 * 4 bytes

const B TCP_OPTIONS_MAX_SIZE     = B(40);  // 40 bytes, 15 * 4 bytes (15 is the largest number in 4 bits length data offset field), TCP_MAX_HEADER_OCTETS - TCP_HEADER_OCTETS = 40
const B TCP_OPTION_HEAD_SIZE = B(2);       // 2 bytes, type and length
const B TCP_OPTION_SACK_MIN_SIZE = B(10);  // 10 bytes, option length = 8 * n + 2 bytes (NOP)
const B TCP_OPTION_SACK_ENTRY_SIZE = B(8); // sack entry size
const B TCP_OPTION_TS_SIZE       = B(12);  // 12 bytes, option length = 10 bytes + 2 bytes (NOP)
// }}

/**
 * Enum generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:39</tt> by nedtool.
 * <pre>
 * enum TcpConstants
 * {
 *     // maximum allowed sack entry number, if no other options are used
 *     TCP_MAX_SACK_ENTRIES = 4;
 * }
 * </pre>
 */
enum TcpConstants {
    TCP_MAX_SACK_ENTRIES = 4
};

/**
 * Enum generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:52</tt> by nedtool.
 * <pre>
 * //
 * // TCP Option Numbers
 * // Reference: http://www.iana.org/assignments/tcp-parameters/
 * // Date: 2011-07-02
 * //
 * // Note: Options not yet implemented should stay commented out
 * //
 * enum TcpOptionNumbers
 * {
 *     TCPOPTION_END_OF_OPTION_LIST = 0;                   // RFC 793, LENGTH: 1 Byte
 *     TCPOPTION_NO_OPERATION = 1;                         // RFC 793, LENGTH: 1 Byte
 *     TCPOPTION_MAXIMUM_SEGMENT_SIZE = 2;                 // RFC 793, LENGTH: 4 Bytes
 *     TCPOPTION_WINDOW_SCALE = 3;                         // RFC 1323, LENGTH: 3 Bytes
 *     TCPOPTION_SACK_PERMITTED = 4;                       // RFC 2018, LENGTH: 2 Bytes
 *     TCPOPTION_SACK = 5;                                 // RFC 2018, LENGTH: N (max. N = 4) 8 * n + 2 Bytes  => 32 + 2 + 2 * NOP = 36 Bytes; If TIMESTAMP option is used with SACK: max. n = 3 => 12 Bytes (for Timestamp) + 28 Bytes (for SACK) = 40 Bytes
 *     //    TCPOPTION_ECHO = 6;                               // (obsoleted by option 8) RFC 1072 & RFC 6247, LENGTH: 6 Bytes
 *     //    TCPOPTION_ECHO_REPLY = 7;                         // (obsoleted by option 8) RFC 1072 & RFC 6247, LENGTH: 6 Bytes
 *     TCPOPTION_TIMESTAMP = 8;                            // RFC 1323, LENGTH: 10 Bytes
 * }
 * </pre>
 */
enum TcpOptionNumbers {
    TCPOPTION_END_OF_OPTION_LIST = 0,
    TCPOPTION_NO_OPERATION = 1,
    TCPOPTION_MAXIMUM_SEGMENT_SIZE = 2,
    TCPOPTION_WINDOW_SCALE = 3,
    TCPOPTION_SACK_PERMITTED = 4,
    TCPOPTION_SACK = 5,
    TCPOPTION_TIMESTAMP = 8
};

/**
 * Class generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:92</tt> by nedtool.
 * <pre>
 * //
 * // This structure represents a single SACK (selective acknowledgment):
 * //
 * class SackItem extends cObject
 * {
 *     unsigned int start;     // start seq no. of sack block
 *     unsigned int end;       // end seq no. of sack block
 * }
 * </pre>
 */
class INET_API SackItem : public ::omnetpp::cObject
{
  protected:
    unsigned int start = 0;
    unsigned int end = 0;

  private:
    void copy(const SackItem& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SackItem&);

  public:
    SackItem();
    SackItem(const SackItem& other);
    virtual ~SackItem();
    SackItem& operator=(const SackItem& other);
    virtual SackItem *dup() const override {return new SackItem(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getStart() const;
    virtual void setStart(unsigned int start);
    virtual unsigned int getEnd() const;
    virtual void setEnd(unsigned int end);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SackItem& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SackItem& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:98</tt> by nedtool.
 * <pre>
 * class Sack extends SackItem
 * {
 * }
 * </pre>
 */
class INET_API Sack : public ::inet::tcp::SackItem
{
  protected:

  private:
    void copy(const Sack& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Sack&);

  public:
    Sack();
    Sack(const Sack& other);
    virtual ~Sack();
    Sack& operator=(const Sack& other);
    virtual Sack *dup() const override {return new Sack(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods

  public:
    Sack(unsigned int start_par, unsigned int end_par) { setSegment(start_par, end_par); }
    virtual bool empty() const;
    virtual bool contains(const Sack& other) const;
    virtual void clear();
    virtual void setSegment(unsigned int start_par, unsigned int end_par);
    virtual std::string str() const override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Sack& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Sack& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:113</tt> by nedtool.
 * <pre>
 * // Header Options (optional):
 * class TcpOption extends cObject
 * {
 *     TcpOptionNumbers kind;            // option kind
 *     unsigned short length = 1;                    // option length
 * }
 * </pre>
 */
class INET_API TcpOption : public ::omnetpp::cObject
{
  protected:
    inet::tcp::TcpOptionNumbers kind = static_cast<inet::tcp::TcpOptionNumbers>(-1);
    unsigned short length = 1;

  private:
    void copy(const TcpOption& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TcpOption&);

  public:
    TcpOption();
    TcpOption(const TcpOption& other);
    virtual ~TcpOption();
    TcpOption& operator=(const TcpOption& other);
    virtual TcpOption *dup() const override {return new TcpOption(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual inet::tcp::TcpOptionNumbers getKind() const;
    virtual void setKind(inet::tcp::TcpOptionNumbers kind);
    virtual unsigned short getLength() const;
    virtual void setLength(unsigned short length);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TcpOption& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TcpOption& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:119</tt> by nedtool.
 * <pre>
 * class TcpOptionEnd extends TcpOption
 * {
 *     kind = TCPOPTION_END_OF_OPTION_LIST;
 *     length = 1;
 * }
 * </pre>
 */
class INET_API TcpOptionEnd : public ::inet::tcp::TcpOption
{
  protected:

  private:
    void copy(const TcpOptionEnd& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TcpOptionEnd&);

  public:
    TcpOptionEnd();
    TcpOptionEnd(const TcpOptionEnd& other);
    virtual ~TcpOptionEnd();
    TcpOptionEnd& operator=(const TcpOptionEnd& other);
    virtual TcpOptionEnd *dup() const override {return new TcpOptionEnd(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TcpOptionEnd& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TcpOptionEnd& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:125</tt> by nedtool.
 * <pre>
 * class TcpOptionNop extends TcpOption
 * {
 *     kind = TCPOPTION_NO_OPERATION;
 *     length = 1;
 * }
 * </pre>
 */
class INET_API TcpOptionNop : public ::inet::tcp::TcpOption
{
  protected:

  private:
    void copy(const TcpOptionNop& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TcpOptionNop&);

  public:
    TcpOptionNop();
    TcpOptionNop(const TcpOptionNop& other);
    virtual ~TcpOptionNop();
    TcpOptionNop& operator=(const TcpOptionNop& other);
    virtual TcpOptionNop *dup() const override {return new TcpOptionNop(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TcpOptionNop& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TcpOptionNop& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:131</tt> by nedtool.
 * <pre>
 * class TcpOptionMaxSegmentSize extends TcpOption
 * {
 *     kind = TCPOPTION_MAXIMUM_SEGMENT_SIZE;
 *     length = 4;
 *     uint16_t maxSegmentSize;   // uint16_t
 * }
 * </pre>
 */
class INET_API TcpOptionMaxSegmentSize : public ::inet::tcp::TcpOption
{
  protected:
    uint16_t maxSegmentSize = 0;

  private:
    void copy(const TcpOptionMaxSegmentSize& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TcpOptionMaxSegmentSize&);

  public:
    TcpOptionMaxSegmentSize();
    TcpOptionMaxSegmentSize(const TcpOptionMaxSegmentSize& other);
    virtual ~TcpOptionMaxSegmentSize();
    TcpOptionMaxSegmentSize& operator=(const TcpOptionMaxSegmentSize& other);
    virtual TcpOptionMaxSegmentSize *dup() const override {return new TcpOptionMaxSegmentSize(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint16_t getMaxSegmentSize() const;
    virtual void setMaxSegmentSize(uint16_t maxSegmentSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TcpOptionMaxSegmentSize& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TcpOptionMaxSegmentSize& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:138</tt> by nedtool.
 * <pre>
 * class TcpOptionWindowScale extends TcpOption
 * {
 *     kind = TCPOPTION_WINDOW_SCALE;
 *     length = 3;
 *     unsigned short windowScale;   // uint8_t
 * }
 * </pre>
 */
class INET_API TcpOptionWindowScale : public ::inet::tcp::TcpOption
{
  protected:
    unsigned short windowScale = 0;

  private:
    void copy(const TcpOptionWindowScale& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TcpOptionWindowScale&);

  public:
    TcpOptionWindowScale();
    TcpOptionWindowScale(const TcpOptionWindowScale& other);
    virtual ~TcpOptionWindowScale();
    TcpOptionWindowScale& operator=(const TcpOptionWindowScale& other);
    virtual TcpOptionWindowScale *dup() const override {return new TcpOptionWindowScale(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned short getWindowScale() const;
    virtual void setWindowScale(unsigned short windowScale);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TcpOptionWindowScale& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TcpOptionWindowScale& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:145</tt> by nedtool.
 * <pre>
 * class TcpOptionSackPermitted extends TcpOption
 * {
 *     kind = TCPOPTION_SACK_PERMITTED;
 *     length = 2;
 * }
 * </pre>
 */
class INET_API TcpOptionSackPermitted : public ::inet::tcp::TcpOption
{
  protected:

  private:
    void copy(const TcpOptionSackPermitted& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TcpOptionSackPermitted&);

  public:
    TcpOptionSackPermitted();
    TcpOptionSackPermitted(const TcpOptionSackPermitted& other);
    virtual ~TcpOptionSackPermitted();
    TcpOptionSackPermitted& operator=(const TcpOptionSackPermitted& other);
    virtual TcpOptionSackPermitted *dup() const override {return new TcpOptionSackPermitted(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TcpOptionSackPermitted& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TcpOptionSackPermitted& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:151</tt> by nedtool.
 * <pre>
 * class TcpOptionSack extends TcpOption
 * {
 *     kind = TCPOPTION_SACK;
 *     length = 2;     // 2 + getSackArraySize() * 8
 *     SackItem sackItem[];
 * }
 * </pre>
 */
class INET_API TcpOptionSack : public ::inet::tcp::TcpOption
{
  protected:
    SackItem *sackItem = nullptr;
    size_t sackItem_arraysize = 0;

  private:
    void copy(const TcpOptionSack& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TcpOptionSack&);

  public:
    TcpOptionSack();
    TcpOptionSack(const TcpOptionSack& other);
    virtual ~TcpOptionSack();
    TcpOptionSack& operator=(const TcpOptionSack& other);
    virtual TcpOptionSack *dup() const override {return new TcpOptionSack(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setSackItemArraySize(size_t size);
    virtual size_t getSackItemArraySize() const;
    virtual const SackItem& getSackItem(size_t k) const;
    virtual SackItem& getSackItemForUpdate(size_t k) { return const_cast<SackItem&>(const_cast<TcpOptionSack*>(this)->getSackItem(k));}
    virtual void setSackItem(size_t k, const SackItem& sackItem);
    virtual void insertSackItem(const SackItem& sackItem);
    virtual void insertSackItem(size_t k, const SackItem& sackItem);
    virtual void eraseSackItem(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TcpOptionSack& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TcpOptionSack& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:158</tt> by nedtool.
 * <pre>
 * class TcpOptionTimestamp extends TcpOption
 * {
 *     kind = TCPOPTION_TIMESTAMP;
 *     length = 10;
 *     uint32_t senderTimestamp;
 *     uint32_t echoedTimestamp;
 * }
 * </pre>
 */
class INET_API TcpOptionTimestamp : public ::inet::tcp::TcpOption
{
  protected:
    uint32_t senderTimestamp = 0;
    uint32_t echoedTimestamp = 0;

  private:
    void copy(const TcpOptionTimestamp& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TcpOptionTimestamp&);

  public:
    TcpOptionTimestamp();
    TcpOptionTimestamp(const TcpOptionTimestamp& other);
    virtual ~TcpOptionTimestamp();
    TcpOptionTimestamp& operator=(const TcpOptionTimestamp& other);
    virtual TcpOptionTimestamp *dup() const override {return new TcpOptionTimestamp(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint32_t getSenderTimestamp() const;
    virtual void setSenderTimestamp(uint32_t senderTimestamp);
    virtual uint32_t getEchoedTimestamp() const;
    virtual void setEchoedTimestamp(uint32_t echoedTimestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TcpOptionTimestamp& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TcpOptionTimestamp& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:166</tt> by nedtool.
 * <pre>
 * class TcpOptionUnknown extends TcpOption
 * {
 *     kind = static_cast<TcpOptionNumbers>(-1);
 *     uint8_t bytes[];
 * }
 * </pre>
 */
class INET_API TcpOptionUnknown : public ::inet::tcp::TcpOption
{
  protected:
    uint8_t *bytes = nullptr;
    size_t bytes_arraysize = 0;

  private:
    void copy(const TcpOptionUnknown& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TcpOptionUnknown&);

  public:
    TcpOptionUnknown();
    TcpOptionUnknown(const TcpOptionUnknown& other);
    virtual ~TcpOptionUnknown();
    TcpOptionUnknown& operator=(const TcpOptionUnknown& other);
    virtual TcpOptionUnknown *dup() const override {return new TcpOptionUnknown(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setBytesArraySize(size_t size);
    virtual size_t getBytesArraySize() const;
    virtual uint8_t getBytes(size_t k) const;
    virtual void setBytes(size_t k, uint8_t bytes);
    virtual void insertBytes(uint8_t bytes);
    virtual void insertBytes(size_t k, uint8_t bytes);
    virtual void eraseBytes(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TcpOptionUnknown& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TcpOptionUnknown& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/transportlayer/tcp_common/TcpHeader.msg:186</tt> by nedtool.
 * <pre>
 * //
 * // Represents a TCP segment, to be used with the ~TCP module.
 * //
 * // TCP header fields not explicitly modelled: work on going
 * // - Data Offset (number of 32 bit words in the header): represented
 * //   by cMessage::length().
 * // - Reserved (reserved for future use)
 * // - Checksum (header checksum): modelled by cMessage::hasBitError()
 * // - Header Options: Currently only EOL, NOP, MSS, WS, SACK_PERMITTED, SACK and TS are implemented
 * // - Padding
 * //
 * // cMessage::getKind() may be set to an arbitrary value: TCP entities will
 * // ignore it and use only the header fields (synBit, ackBit, rstBit).
 * //
 * class TcpHeader extends TransportHeaderBase
 * {
 *     chunkLength = TCP_MIN_HEADER_LENGTH;
 * 
 *     // Source Port
 *     unsigned short srcPort;
 * 
 *     // Destination Port
 *     unsigned short destPort;
 * 
 *     // Sequence Number: first sequence number of the first data octet
 *     // in the respective segment (except if SYN is set; then the the
 *     // seq. number is the initial seq. number (ISS) and the first data
 *     // octet is ISS + 1)
 *     unsigned int sequenceNo;
 * 
 *     // Acknowledgement Number: if ACK flag is set, this field contains
 *     // the next sequence number the sender of this segment is expecting
 *     // to receive
 *     unsigned int ackNo;
 * 
 *     // TCP Header Length - default: 20 bytes
 *     // if header options are used the headerLength is greater than 20 bytes (default)
 *     B headerLength = TCP_MIN_HEADER_LENGTH; // TCP_MIN_HEADER_LENGTH = 20 bytes
 * 
 *     bool urgBit; // URG: urgent pointer field significant if set
 *     bool ackBit; // ACK: ackNo significant if set
 *     bool pshBit; // PSH: push function
 *     bool rstBit; // RST: reset the connection
 *     bool synBit; // SYN: synchronize seq. numbers
 *     bool finBit; // FIN: finish - no more data from sender
 * 
 *     // Window Size: the number of data octets beginning with the one indicated
 *     // in the acknowledgement field which the sender of this segment is
 *     // willing to accept
 *     unsigned short window;
 * 
 *     // Urgent Pointer: communicates the current value of the urgent pointer
 *     // as a positive offset from the sequence number in this segment. The
 *     // urgent pointer points to the sequence number of the octet following
 *     // the urgent data. This field is only be interpreted in segments with
 *     // the URG control bit set.
 *     unsigned short urgentPointer;
 * 
 *     uint16_t crc = 0;
 *     CrcMode crcMode = CRC_MODE_UNDEFINED;
 * 
 *     // Header options (optional)
 *     // Currently only EOL, NOP, MSS, WS, SACK_PERMITTED, SACK and TS are implemented
 *     TcpOption *headerOption[] \@owned;
 * }
 * </pre>
 */
class INET_API TcpHeader : public ::inet::TransportHeaderBase
{
  protected:
    unsigned short srcPort = 0;
    unsigned short destPort = 0;
    unsigned int sequenceNo = 0;
    unsigned int ackNo = 0;
    B headerLength = TCP_MIN_HEADER_LENGTH;
    bool urgBit = false;
    bool ackBit = false;
    bool pshBit = false;
    bool rstBit = false;
    bool synBit = false;
    bool finBit = false;
    unsigned short window = 0;
    unsigned short urgentPointer = 0;
    uint16_t crc = 0;
    inet::CrcMode crcMode = CRC_MODE_UNDEFINED;
    TcpOption * *headerOption = nullptr;
    size_t headerOption_arraysize = 0;

  private:
    void copy(const TcpHeader& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TcpHeader&);

  public:
    TcpHeader();
    TcpHeader(const TcpHeader& other);
    virtual ~TcpHeader();
    TcpHeader& operator=(const TcpHeader& other);
    virtual TcpHeader *dup() const override {return new TcpHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned short getSrcPort() const;
    virtual void setSrcPort(unsigned short srcPort);
    virtual unsigned short getDestPort() const;
    virtual void setDestPort(unsigned short destPort);
    virtual unsigned int getSequenceNo() const;
    virtual void setSequenceNo(unsigned int sequenceNo);
    virtual unsigned int getAckNo() const;
    virtual void setAckNo(unsigned int ackNo);
    virtual B getHeaderLength() const;
    virtual void setHeaderLength(B headerLength);
    virtual bool getUrgBit() const;
    virtual void setUrgBit(bool urgBit);
    virtual bool getAckBit() const;
    virtual void setAckBit(bool ackBit);
    virtual bool getPshBit() const;
    virtual void setPshBit(bool pshBit);
    virtual bool getRstBit() const;
    virtual void setRstBit(bool rstBit);
    virtual bool getSynBit() const;
    virtual void setSynBit(bool synBit);
    virtual bool getFinBit() const;
    virtual void setFinBit(bool finBit);
    virtual unsigned short getWindow() const;
    virtual void setWindow(unsigned short window);
    virtual unsigned short getUrgentPointer() const;
    virtual void setUrgentPointer(unsigned short urgentPointer);
    virtual uint16_t getCrc() const;
    virtual void setCrc(uint16_t crc);
    virtual inet::CrcMode getCrcMode() const;
    virtual void setCrcMode(inet::CrcMode crcMode);
    virtual void setHeaderOptionArraySize(size_t size);
    virtual size_t getHeaderOptionArraySize() const;
    virtual const TcpOption * getHeaderOption(size_t k) const;
    virtual TcpOption * getHeaderOptionForUpdate(size_t k) { handleChange();return const_cast<TcpOption *>(const_cast<TcpHeader*>(this)->getHeaderOption(k));}
    virtual TcpOption * dropHeaderOption(size_t k);
    virtual void setHeaderOption(size_t k, TcpOption * headerOption);
    virtual void insertHeaderOption(TcpOption * headerOption);
    virtual void insertHeaderOption(size_t k, TcpOption * headerOption);
    virtual void eraseHeaderOption(size_t k);

  public:
    /**
     * Returns RFC 793 specified SEG.LEN:
     *     SEG.LEN = the number of octets occupied by the data in the segment
     *               (counting SYN and FIN)
     *
     */
    uint32_t getSynFinLen() const { return (finBit ? 1 : 0) + (synBit ? 1 : 0); }

    /** Calculate Length of TCP Options Array in bytes */
    virtual B getHeaderOptionArrayLength();

    /** Drops all TCP options of the TCP segment */
    virtual void dropHeaderOptions();

    // implements TransportHeaderBase functions:
    virtual unsigned int getSourcePort() const override { return getSrcPort(); }
    virtual void setSourcePort(unsigned int port) override { setSrcPort(port); }
    virtual unsigned int getDestinationPort() const override { return getDestPort(); }
    virtual void setDestinationPort(unsigned int port) override { setDestPort(port); }

    virtual std::string str() const override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TcpHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TcpHeader& obj) {obj.parsimUnpack(b);}

} // namespace tcp
} // namespace inet

#endif // ifndef __INET__TCP_TCPHEADER_M_H

