#!/bin/bash

NESTING=..
INET=$NESTING/../inet
D=$([ "$MODE" == "debug" ] && echo "_dbg" || echo "")

./nesting$D -m -u Cmdenv -n .:$NESTING/src:$INET/src -l $NESTING/src/nesting -l $INET/src/INET "$1"
