//
// Generated file, do not edit! Created by nedtool 5.6 from inet/physicallayer/ieee80211/mode/IIeee80211Mode.msg.
//

#ifndef __INET__PHYSICALLAYER_IIEEE80211MODE_M_H
#define __INET__PHYSICALLAYER_IIEEE80211MODE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {
namespace physicallayer {

} // namespace physicallayer
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/physicallayer/contract/packetlevel/IModulation_m.h" // import inet.physicallayer.contract.packetlevel.IModulation

// cplusplus {{
#include "inet/physicallayer/ieee80211/mode/IIeee80211Mode.h"
#include "inet/physicallayer/ieee80211/mode/Ieee80211ModeSet.h"
#include "inet/physicallayer/ieee80211/mode/Ieee80211OfdmModulation.h"
// }}


namespace inet {
namespace physicallayer {

} // namespace physicallayer
} // namespace inet

#endif // ifndef __INET__PHYSICALLAYER_IIEEE80211MODE_M_H

