//
// Generated file, do not edit! Created by nedtool 5.6 from inet/networklayer/common/DscpTag.msg.
//

#ifndef __INET_DSCPTAG_M_H
#define __INET_DSCPTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class DscpTagBase;
class DscpReq;
class DscpInd;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace inet {

/**
 * Class generated from <tt>inet/networklayer/common/DscpTag.msg:14</tt> by nedtool.
 * <pre>
 * //
 * // This is an abstract base class that should not be directly added as a tag.
 * //
 * class DscpTagBase extends TagBase
 * {
 *     int differentiatedServicesCodePoint = -1; // differentiated services code point
 * }
 * </pre>
 */
class INET_API DscpTagBase : public ::inet::TagBase
{
  protected:
    int differentiatedServicesCodePoint = -1;

  private:
    void copy(const DscpTagBase& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DscpTagBase&);

  public:
    DscpTagBase();
    DscpTagBase(const DscpTagBase& other);
    virtual ~DscpTagBase();
    DscpTagBase& operator=(const DscpTagBase& other);
    virtual DscpTagBase *dup() const override {return new DscpTagBase(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getDifferentiatedServicesCodePoint() const;
    virtual void setDifferentiatedServicesCodePoint(int differentiatedServicesCodePoint);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DscpTagBase& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DscpTagBase& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/networklayer/common/DscpTag.msg:23</tt> by nedtool.
 * <pre>
 * //
 * // This request determines the differentiated services code point that should be used to transmit the packet.
 * // It may be present on a packet from the application to the network protocol.
 * //
 * class DscpReq extends DscpTagBase
 * {
 * }
 * </pre>
 */
class INET_API DscpReq : public ::inet::DscpTagBase
{
  protected:

  private:
    void copy(const DscpReq& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DscpReq&);

  public:
    DscpReq();
    DscpReq(const DscpReq& other);
    virtual ~DscpReq();
    DscpReq& operator=(const DscpReq& other);
    virtual DscpReq *dup() const override {return new DscpReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DscpReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DscpReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/networklayer/common/DscpTag.msg:31</tt> by nedtool.
 * <pre>
 * //
 * // This indication specifies the differentiated services code point that was used to receive the packet.
 * // It may be present on a packet from the network protocol to the application.
 * //
 * class DscpInd extends DscpTagBase
 * {
 * }
 * </pre>
 */
class INET_API DscpInd : public ::inet::DscpTagBase
{
  protected:

  private:
    void copy(const DscpInd& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DscpInd&);

  public:
    DscpInd();
    DscpInd(const DscpInd& other);
    virtual ~DscpInd();
    DscpInd& operator=(const DscpInd& other);
    virtual DscpInd *dup() const override {return new DscpInd(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DscpInd& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DscpInd& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_DSCPTAG_M_H

