//
// Generated file, do not edit! Created by nedtool 5.6 from inet/networklayer/common/EcnTag.msg.
//

#ifndef __INET_ECNTAG_M_H
#define __INET_ECNTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class EcnTagBase;
class EcnReq;
class EcnInd;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace inet {

/**
 * Class generated from <tt>inet/networklayer/common/EcnTag.msg:14</tt> by nedtool.
 * <pre>
 * //
 * // This is an abstract base class that should not be directly added as a tag.
 * //
 * class EcnTagBase extends TagBase
 * {
 *     int explicitCongestionNotification = -1; // explicit congestion notification
 * }
 * </pre>
 */
class INET_API EcnTagBase : public ::inet::TagBase
{
  protected:
    int explicitCongestionNotification = -1;

  private:
    void copy(const EcnTagBase& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EcnTagBase&);

  public:
    EcnTagBase();
    EcnTagBase(const EcnTagBase& other);
    virtual ~EcnTagBase();
    EcnTagBase& operator=(const EcnTagBase& other);
    virtual EcnTagBase *dup() const override {return new EcnTagBase(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getExplicitCongestionNotification() const;
    virtual void setExplicitCongestionNotification(int explicitCongestionNotification);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EcnTagBase& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EcnTagBase& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/networklayer/common/EcnTag.msg:22</tt> by nedtool.
 * <pre>
 * //
 * // This request determines the explicit congestion notification that should be used to transmit the packet.
 * //
 * class EcnReq extends EcnTagBase
 * {
 * }
 * </pre>
 */
class INET_API EcnReq : public ::inet::EcnTagBase
{
  protected:

  private:
    void copy(const EcnReq& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EcnReq&);

  public:
    EcnReq();
    EcnReq(const EcnReq& other);
    virtual ~EcnReq();
    EcnReq& operator=(const EcnReq& other);
    virtual EcnReq *dup() const override {return new EcnReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EcnReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EcnReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/networklayer/common/EcnTag.msg:29</tt> by nedtool.
 * <pre>
 * //
 * // This indication specifies the explicit congestion notification that was used to receive the packet.
 * //
 * class EcnInd extends EcnTagBase
 * {
 * }
 * </pre>
 */
class INET_API EcnInd : public ::inet::EcnTagBase
{
  protected:

  private:
    void copy(const EcnInd& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EcnInd&);

  public:
    EcnInd();
    EcnInd(const EcnInd& other);
    virtual ~EcnInd();
    EcnInd& operator=(const EcnInd& other);
    virtual EcnInd *dup() const override {return new EcnInd(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EcnInd& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EcnInd& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_ECNTAG_M_H

